
import React, { createContext, useState, useContext, ReactNode, useCallback } from 'react';

// Define translations directly in the file
const translations = {
  en: {
    // Header
    slogan: "Your health, in a scan.",
    // Dashboard
    familyMembers: "Family Members",
    addMember: "Add Member",
    assignPrePrintedQrButton: "Assign Pre-Printed QR",
    googleDriveBackup: "Google Drive Backup",
    savingChanges: "Saving changes...",
    allChangesSaved: "All changes saved to Drive",
    backupFailed: "Backup failed",
    lastBackup: "Last backup:",
    openDrive: "Open Drive",
    restore: "Restore",
    signedIn: "Signed In",
    signOut: "Sign Out",
    connectToGoogle: "Connect to Google Drive",
    noFamilyMembers: "No family members yet",
    getStarted: "Get started by adding your own family member, or load a demo set.",
    addNewMember: "Add New Member",
    loadDemoData: "Load Demo Data",
    adminLogin: "Admin login",
    adminLogout: "Exit admin",
    adminModeLabel: "Admin mode",
    // AddPatientModal
    addNewFamilyMember: "Add New Family Member",
    fullName: "Full Name",
    dateOfBirth: "Date of Birth",
    bloodType: "Blood Type",
    profilePhoto: "Profile Photo",
    upload: "Upload",
    cancel: "Cancel",
    // PatientProfile
    backToDashboard: "Back to Dashboard",
    changePhoto: "Change Photo",
    mainCloudLink: "Main Cloud Storage Link",
    allergies: "Allergies",
    currentMedications: "Current Medications",
    lastVisitDate: "Last Visit Date",
    separateWithCommas: "Separate with commas.",
    changeQRCode: "Change QR Code",
    uploadQRCode: "Upload QR Code",
    useGeneratedQRCode: "Use Generated QR Code",
    dob: "DOB",
    viewMainCloud: "View Main Cloud Storage",
    patientQRCode: "Patient QR Code",
    qrScanInstruction: "Healthcare providers can scan this code to access the patient's medical records instantly.",
    share: "Share",
    files: "Files",
    print: "Print",
    pdf: "PDF",
    generating: "Generating...",
    editMedicalFolders: "Edit Medical Folders",
    editFoldersInstruction: "Paste the public share link for each cloud storage folder (e.g., Google Drive, Dropbox). For doctor access, set folder permissions to \"Anyone with the link\".",
    browse: "Browse",
    saveAllChanges: "Save All Changes",
    medicalSummary: "Medical Summary",
    noneReported: "None reported",
    notRecorded: "Not recorded",
    medicalFolders: "Medical Folders",
    scanFor: "Scan for {categoryName}",
    // Public View
    patientNotFound: "Patient Not Found",
    patientNotFoundDesc: "The requested patient record does not exist or the link is invalid.",
    redirecting: "Redirecting to Medical Records...",
    redirectingDesc: "You are being redirected to the patient's main document folder.",
    clickHere: "please click here",
    secureRecord: "QRate Secure Record",
    keyMedicalInfo: "Key Medical Information",
    lastKnownVisit: "Last Known Visit",
    noMainFolder: "No main document folder is linked for this patient. Click a category below to view specific records.",
    noRecordsLinked: "No medical records have been linked for this patient.",
    // Toasts (App.tsx)
    profileSavedAndUpdate: "Profile saved and QR code updated with new information.",
    profileUpdated: "Patient profile updated!",
    noBackupFound: "No backup found to restore.",
    confirmRestore: "Are you sure? This will overwrite your current local data with the data from your last backup.",
    restoredSuccess: "Data successfully restored!",
    confirmDemo: "This will replace any existing data with the demo family. Are you sure?",
    demoLoaded: "Demo data loaded!",
    // PrintableView
    patientSummary: "QRate Patient Summary",
    generatedOn: "Generated on:",
    scanForFullRecord: "Scan for Full Digital Record",
    directFolderAccess: "Direct Folder Access",
    noLinkProvided: "No Link Provided",
    printableFooter: "This document may contain sensitive personal health information. Please handle it with care and store it securely.",
    emergencyId: "QRate Emergency ID",
    emergencyIdDesc: "Instructions: Cut out the cards below, fold in half, and laminate. Keep in your wallet for emergencies.",
    nameLabel: "Name",
    scanForFullInfo: "Scan for full records, allergies, & medications.",
    // Medical Categories
    category_general_practice: "General Practice",
    category_dental: "Dental",
    category_xrays: "X-Rays & Imaging",
    category_lab: "Lab Results",
    category_rx: "Prescriptions",
    category_spec: "Specialist Reports",
    // Assign Pre-Printed QR
    assignPrePrintedQrTitle: "Assign Pre-Printed QR",
    assignPrePrintedQrSubtitle: "Scan or enter a pre-printed QR code and link it to a family member.",
    assignQrStep1: "Step 1 · Capture the QR token",
    assignQrStep1Desc: "Scan the pre-printed QR with your phone or type the token printed on the card or sticker.",
    assignQrTokenLabel: "QR token or card code",
    assignQrScanWithCamera: "Scan with camera (coming soon)",
    assignQrUploadImage: "Upload QR image (coming soon)",
    comingSoon: "Coming soon",
    assignQrStep2: "Step 2 · Assign to a member",
    assignQrExistingMember: "Existing member",
    assignQrNewMember: "New member",
    assignQrSelectLabel: "Select a family member",
    assignQrSelectPlaceholder: "Choose a person to receive this QR",
    assignQrExistingHint: "Their previous QR, if any, will be safely inactivated.",
    assignQrSoldByLabel: "Sold by / Assigned by (optional)",
    assignQrSoldByPlaceholder: "Name or ID of sales agent",
    assignQrPrimaryCta: "Assign QR",
    assignQrInventorySummary: "QR inventory snapshot",
    assignQrInventorySummaryDesc: "These numbers come from your local device. A future update can sync this with a central dashboard.",
    assignQrAssignedCount: "Assigned QRs",
    assignQrUnassignedCount: "Unassigned QRs",
    assignQrTipTitle: "Pre-printed QR = unassigned token",
    assignQrTipBody: "Treat each printed QR like a serial number. At the moment of sale, you simply assign that token to a person—no need to print on demand.",
    assignQrEnterToken: "Please enter the QR token printed on the card.",
    assignQrSelectMember: "Please select a family member to assign this QR to.",
    assignQrFillNewMember: "Please fill in the new member's basic details.",
    assignQrSuccessExisting: "QR assigned to member.",
    assignQrSuccessNew: "QR assigned and new member created.",
    qrTokenNotFound: "QR token not found in inventory.",
    qrTokenAlreadyAssigned: "This QR is already assigned or unavailable.",
    // Generate QR Batch
    generateBatchTitle: "Generate QR Batch",
    generateBatchSubtitle: "Create a batch of pre-printed QR tokens for cards or stickers.",
    generateBatchPrefixLabel: "Prefix",
    generateBatchBatchNameLabel: "Batch name",
    generateBatchQuantityLabel: "Quantity",
    generateBatchStartNumberLabel: "Starting number",
    generateBatchGenerateButton: "Generate batch",
    generateBatchExportPdfButton: "Export PDF",
    generateBatchLastBatchTitle: "Last generated batch",
    generateBatchLastBatchNone: "No batch generated yet in this session.",
    generateBatchLastBatchSummary: "{count} QRs from {firstToken} to {lastToken}",
    generateBatchValidationErrorQuantity: "Quantity must be between 1 and 10,000.",
    generateBatchValidationErrorBatchName: "Batch name is required.",
    generateBatchValidationErrorStartNumber: "Start number must be 1 or greater.",
    generateBatchValidationErrorDuplicate: "A QR token from this batch already exists: {token}",
    generateBatchNoRecordsForPdf: "Generate a batch before exporting to PDF.",
    generateBatchPdfError: "An error occurred while generating the batch PDF.",
    cameraNotSupported: "Camera QR scanning is not supported in this browser. Please type the code manually.",
    cameraPermissionDenied: "Could not access the camera. Please check browser permissions.",
    cameraScanHint: "Point the printed QR inside the frame. The code will be read automatically.",
    stopCameraScan: "Stop camera",
    adminEnterPinPrompt: "Enter admin PIN to unlock the batch generator:",
    adminInvalidPin: "Invalid admin PIN.",
    adminModeEnabled: "Admin mode enabled.",
    adminModeDisabled: "Admin mode disabled.",
    adminAccessRequired: "Admin access required to generate QR batches.",
  },
  es: {
    // Header
    slogan: "Tu salud, en un escaneo.",
    // Dashboard
    familyMembers: "Miembros de la Familia",
    addMember: "Añadir Miembro",
    assignPrePrintedQrButton: "Asignar QR Preimpreso",
    googleDriveBackup: "Copia de Seguridad de Google Drive",
    savingChanges: "Guardando cambios...",
    allChangesSaved: "Todos los cambios guardados en Drive",
    backupFailed: "Falló la copia de seguridad",
    lastBackup: "Última copia:",
    openDrive: "Abrir Drive",
    restore: "Restaurar",
    signedIn: "Sesión Iniciada",
    signOut: "Cerrar Sesión",
    connectToGoogle: "Conectar a Google Drive",
    noFamilyMembers: "Aún no hay miembros en la familia",
    getStarted: "Comienza añadiendo un miembro de tu familia, o carga datos de demostración.",
    addNewMember: "Añadir Nuevo Miembro",
    loadDemoData: "Cargar Datos de Muestra",
    adminLogin: "Acceso de administrador",
    adminLogout: "Salir de administrador",
    adminModeLabel: "Modo administrador",
    // AddPatientModal
    addNewFamilyMember: "Añadir Nuevo Miembro",
    fullName: "Nombre Completo",
    dateOfBirth: "Fecha de Nacimiento",
    bloodType: "Tipo de Sangre",
    profilePhoto: "Foto de Perfil",
    upload: "Subir",
    cancel: "Cancelar",
    // PatientProfile
    backToDashboard: "Volver al Panel",
    changePhoto: "Cambiar Foto",
    mainCloudLink: "Enlace Principal de Almacenamiento",
    allergies: "Alergias",
    currentMedications: "Medicamentos Actuales",
    lastVisitDate: "Fecha de Última Visita",
    separateWithCommas: "Separar con comas.",
    changeQRCode: "Cambiar Código QR",
    uploadQRCode: "Subir Código QR",
    useGeneratedQRCode: "Usar Código QR Generado",
    dob: "Fecha de Nac.",
    viewMainCloud: "Ver Almacenamiento Principal",
    patientQRCode: "Código QR del Paciente",
    qrScanInstruction: "Los proveedores de salud pueden escanear este código para acceder a los registros médicos del paciente al instante.",
    share: "Compartir",
    files: "Archivos",
    print: "Imprimir",
    pdf: "PDF",
    generating: "Generando...",
    editMedicalFolders: "Editar Carpetas Médicas",
    editFoldersInstruction: "Pega el enlace público para compartir de cada carpeta (ej. Google Drive, Dropbox). Para el acceso de los doctores, establece los permisos de la carpeta a \"Cualquier persona con el enlace\".",
    browse: "Buscar",
    saveAllChanges: "Guardar Todos los Cambios",
    medicalSummary: "Resumen Médico",
    noneReported: "Ninguna reportada",
    notRecorded: "No registrado",
    medicalFolders: "Carpetas Médicas",
    scanFor: "Escanear para {categoryName}",
    // Public View
    patientNotFound: "Paciente no Encontrado",
    patientNotFoundDesc: "El registro del paciente solicitado no existe o el enlace no es válido.",
    redirecting: "Redirigiendo a los Registros Médicos...",
    redirectingDesc: "Estás siendo redirigido a la carpeta principal de documentos del paciente.",
    clickHere: "por favor, haz clic aquí",
    secureRecord: "Registro Seguro QRate",
    keyMedicalInfo: "Información Médica Clave",
    lastKnownVisit: "Última Visita Conocida",
    noMainFolder: "No hay una carpeta de documentos principal vinculada para este paciente. Haz clic en una categoría para ver registros específicos.",
    noRecordsLinked: "No se han vinculado registros médicos para este paciente.",
    // Toasts (App.tsx)
    profileSavedAndUpdate: "Perfil guardado y código QR actualizado con nueva información.",
    profileUpdated: "¡Perfil del paciente actualizado!",
    noBackupFound: "No se encontró una copia de seguridad para restaurar.",
    confirmRestore: "¿Estás seguro? Esto sobrescribirá tus datos locales actuales con los de tu última copia de seguridad.",
    restoredSuccess: "¡Datos restaurados con éxito!",
    confirmDemo: "¿Estás seguro? Esto reemplazará los datos existentes con la familia de demostración.",
    demoLoaded: "¡Datos de demostración cargados!",
    // PrintableView
    patientSummary: "Resumen del Paciente QRate",
    generatedOn: "Generado el:",
    scanForFullRecord: "Escanear para Registro Digital Completo",
    directFolderAccess: "Acceso Directo a Carpetas",
    noLinkProvided: "No se Proporcionó Enlace",
    printableFooter: "Este documento puede contener información de salud personal y sensible. Por favor, manéjelo con cuidado y guárdelo de forma segura.",
    emergencyId: "ID de Emergencia QRate",
    emergencyIdDesc: "Instrucciones: Recorte las tarjetas de abajo, dóblelas por la mitad y lamínelas. Guárdelas en su cartera para emergencias.",
    nameLabel: "Nombre",
    scanForFullInfo: "Escanear para registros, alergias y medicamentos.",
    // Medical Categories
    category_general_practice: "Medicina General",
    category_dental: "Dental",
    category_xrays: "Rayos X e Imágenes",
    category_lab: "Resultados de Laboratorio",
    category_rx: "Recetas Médicas",
    category_spec: "Informes de Especialistas",
    // Assign Pre-Printed QR
    assignPrePrintedQrTitle: "Asignar QR Preimpreso",
    assignPrePrintedQrSubtitle: "Escanea o escribe un código QR preimpreso y asígnalo a un miembro de la familia.",
    assignQrStep1: "Paso 1 · Capturar el token del QR",
    assignQrStep1Desc: "Escanea el QR preimpreso con tu teléfono o escribe el código impreso en la tarjeta o etiqueta.",
    assignQrTokenLabel: "Token del QR o código de la tarjeta",
    assignQrScanWithCamera: "Escanear con cámara (próximamente)",
    assignQrUploadImage: "Subir imagen del QR (próximamente)",
    comingSoon: "Próximamente",
    assignQrStep2: "Paso 2 · Asignar a un miembro",
    assignQrExistingMember: "Miembro existente",
    assignQrNewMember: "Nuevo miembro",
    assignQrSelectLabel: "Selecciona un miembro de la familia",
    assignQrSelectPlaceholder: "Elige a la persona que recibirá este QR",
    assignQrExistingHint: "Su QR anterior, si existe, se marcará como inactivo de forma segura.",
    assignQrSoldByLabel: "Vendido por / Asignado por (opcional)",
    assignQrSoldByPlaceholder: "Nombre o ID del agente de ventas",
    assignQrPrimaryCta: "Asignar QR",
    assignQrInventorySummary: "Resumen de inventario de QR",
    assignQrInventorySummaryDesc: "Estas cifras vienen de tu dispositivo local. En una versión futura se podrán sincronizar con un panel central.",
    assignQrAssignedCount: "QR asignados",
    assignQrUnassignedCount: "QR sin asignar",
    assignQrTipTitle: "QR preimpreso = token sin asignar",
    assignQrTipBody: "Trata cada QR impreso como un número de serie. En el momento de la venta, simplemente asignas ese token a una persona, sin necesidad de imprimir bajo demanda.",
    assignQrEnterToken: "Por favor escribe el token del QR impreso en la tarjeta.",
    assignQrSelectMember: "Por favor selecciona un miembro de la familia para asignar este QR.",
    assignQrFillNewMember: "Por favor completa los datos básicos del nuevo miembro.",
    assignQrSuccessExisting: "QR asignado al miembro.",
    assignQrSuccessNew: "QR asignado y nuevo miembro creado.",
    qrTokenNotFound: "Token de QR no encontrado en el inventario.",
    qrTokenAlreadyAssigned: "Este QR ya está asignado o no está disponible.",
    // Generate QR Batch
    generateBatchTitle: "Generar Lote de QR",
    generateBatchSubtitle: "Crea un lote de tokens QR preimpresos para tarjetas o etiquetas.",
    generateBatchPrefixLabel: "Prefijo",
    generateBatchBatchNameLabel: "Nombre del lote",
    generateBatchQuantityLabel: "Cantidad",
    generateBatchStartNumberLabel: "Número inicial",
    generateBatchGenerateButton: "Generar lote",
    generateBatchExportPdfButton: "Exportar PDF",
    generateBatchLastBatchTitle: "Último lote generado",
    generateBatchLastBatchNone: "Aún no se ha generado ningún lote en esta sesión.",
    generateBatchLastBatchSummary: "{count} QRs desde {firstToken} hasta {lastToken}",
    generateBatchValidationErrorQuantity: "La cantidad debe estar entre 1 y 10,000.",
    generateBatchValidationErrorBatchName: "El nombre del lote es obligatorio.",
    generateBatchValidationErrorStartNumber: "El número inicial debe ser 1 o mayor.",
    generateBatchValidationErrorDuplicate: "Ya existe un token de QR de este lote: {token}",
    generateBatchNoRecordsForPdf: "Genera un lote antes de exportar a PDF.",
    generateBatchPdfError: "Ocurrió un error al generar el PDF del lote.",
    cameraNotSupported: "El escaneo de QR con cámara no es compatible en este navegador. Escribe el código manualmente.",
    cameraPermissionDenied: "No se pudo acceder a la cámara. Revisa los permisos del navegador.",
    cameraScanHint: "Apunta el QR impreso dentro del recuadro. El código se leerá automáticamente.",
    stopCameraScan: "Detener cámara",
    adminEnterPinPrompt: "Introduce el PIN de administrador para desbloquear el generador de lotes:",
    adminInvalidPin: "PIN de administrador inválido.",
    adminModeEnabled: "Modo administrador activado.",
    adminModeDisabled: "Modo administrador desactivado.",
    adminAccessRequired: "Se requiere acceso de administrador para generar lotes de QR.",
  }
};

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof translations.en, replacements?: { [key: string]: string }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = useCallback((key: keyof typeof translations.en, replacements?: { [key: string]: string }) => {
    let text = (translations[language] && translations[language][key]) || translations.en[key] || key;
    if (replacements) {
        Object.keys(replacements).forEach(rKey => {
            text = text.replace(`{${rKey}}`, replacements[rKey]);
        });
    }
    return text;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
