
import React, { useState } from 'react';
import { Patient } from '../types';
import { UserIcon } from './icons/Icons';
import { useLanguage } from '../contexts/LanguageContext';

interface AddPatientModalProps {
  isOpen: boolean;
  onClose: () => void;
  // Fix: Corrected the Omit type for onAddPatient to exclude 'medicalCategories' and 'qrCodeData' as they are generated by the parent component.
  onAddPatient: (patient: Omit<Patient, 'id' | 'medicalCategories' | 'qrCodeData'>) => void;
}

const AddPatientModal: React.FC<AddPatientModalProps> = ({ isOpen, onClose, onAddPatient }) => {
  const [name, setName] = useState('');
  const [dateOfBirth, setDateOfBirth] = useState('');
  const [bloodType, setBloodType] = useState('A+');
  const [image, setImage] = useState<string | null>(null);
  const { t } = useLanguage();

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
        const reader = new FileReader();
        reader.onloadend = () => {
            setImage(reader.result as string);
        };
        reader.readAsDataURL(file);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !dateOfBirth) {
        alert("Please fill in all required fields.");
        return;
    }
    onAddPatient({
      name,
      dateOfBirth,
      bloodType,
      profileImageUrl: image || `https://i.pravatar.cc/150?u=${Date.now()}`
    });
    setName('');
    setDateOfBirth('');
    setBloodType('A+');
    setImage(null);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
      <div className="bg-white rounded-lg p-8 shadow-2xl w-full max-w-md m-4">
        <h2 className="text-2xl font-bold mb-6 text-slate-800">{t('addNewFamilyMember')}</h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label htmlFor="name" className="block text-sm font-medium text-slate-700">{t('fullName')}</label>
            <input type="text" id="name" value={name} onChange={(e) => setName(e.target.value)} className="mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md shadow-sm placeholder-slate-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" required />
          </div>
          <div className="mb-4">
            <label htmlFor="dob" className="block text-sm font-medium text-slate-700">{t('dateOfBirth')}</label>
            <input type="date" id="dob" value={dateOfBirth} onChange={(e) => setDateOfBirth(e.target.value)} className="mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" required />
          </div>
          <div className="mb-4">
            <label htmlFor="bloodType" className="block text-sm font-medium text-slate-700">{t('bloodType')}</label>
            <select id="bloodType" value={bloodType} onChange={(e) => setBloodType(e.target.value)} className="mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm">
              {['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map(bt => <option key={bt} value={bt}>{bt}</option>)}
            </select>
          </div>
           <div className="mb-6">
            <label className="block text-sm font-medium text-slate-700">{t('profilePhoto')}</label>
            <div className="mt-2 flex items-center space-x-4">
                <span className="inline-block h-16 w-16 rounded-full overflow-hidden bg-slate-100 ring-2 ring-white">
                {image ? (
                    <img src={image} alt="Profile preview" className="h-full w-full object-cover" />
                ) : (
                    <UserIcon className="h-full w-full text-slate-300" />
                )}
                </span>
                <label htmlFor="photo-upload" className="cursor-pointer bg-white py-2 px-3 border border-slate-300 rounded-md shadow-sm text-sm leading-4 font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    <span>{t('upload')}</span>
                    <input id="photo-upload" name="photo-upload" type="file" className="sr-only" accept="image/*" onChange={handleImageChange} />
                </label>
            </div>
          </div>
          <div className="flex justify-end space-x-4">
            <button type="button" onClick={onClose} className="px-4 py-2 bg-slate-200 text-slate-800 rounded-md hover:bg-slate-300 transition-colors">{t('cancel')}</button>
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors">{t('addMember')}</button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddPatientModal;